---
- name: A simple playbook
  hosts:
    - all
  gather_facts: no
  vars_files:
    - ../inventories/group_vars/x.yml
  tasks:
    - debug: var=encrypted
    - debug: var=other
    - debug: var=myvariable
      #- ping:
